# The URL the site will be built for
base_url = "https://zzzdong.github.io"

# The title of the site
title = "zzzdong的自留地"

# The description of the site
description = "思绪飞扬，在这停留片刻"

author = "zzzdong"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to minify the HTML when building the site
minify_html = false

# Whether to generate an Atom feed
generate_feeds = true

default_language = "zh-cn"

theme = "hacker"

# Taxonomies
taxonomies = [{ name = "tags" }]

[markdown.highlighting]
theme = "dark-plus"

[extra]
title_separator = "|"

# Menu items
menu = [{ url = "/blog", name = "Blog" }]

language_code = "zh-CN"

# Enable OpenGraph metadata
opengraph = true

timezone = "Asia/Shanghai"

# provide link to edit page on github
edit_page = true

# Social links
social_links = [
  { platform = "github", user_id = "zzzdong" },
  { platform = "feed", user_id = true },
]

# GitHub settings that are used to generate the edit page link
[extra.github]
username = "zzzdong"
repo = "zzzdong.github.io"
